---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aax

resources:
  - namespace.yaml
  - configmap.yaml
  - persistent-volumes.yaml
  - ee-base-deployment.yaml
  - ee-builder-deployment.yaml
  - dev-tools-deployment.yaml

images:
  - name: aax/ee-base
    newTag: latest
  - name: aax/ee-builder
    newTag: latest
  - name: aax/dev-tools
    newTag: latest
