---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace
  namespace: aax
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/part-of: aax
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ee-builds
  namespace: aax
  labels:
    app.kubernetes.io/name: ee-builds
    app.kubernetes.io/part-of: aax
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ee-definitions
  namespace: aax
  labels:
    app.kubernetes.io/name: ee-definitions
    app.kubernetes.io/part-of: aax
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-workspace
  namespace: aax
  labels:
    app.kubernetes.io/name: dev-workspace
    app.kubernetes.io/part-of: aax
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
